### CREATE
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "pedro@gmail.com",
    "nome": "pedro",
    "cpf": 1234448398701,
    "dtnasc":"14/07/1989",
    "funcao": 2
}

### FINDALL
GET http://localhost:3000/users

### FINDONE
GET http://localhost:3000/users/2

### UPDATE
PUT http://localhost:3000/users/2
Content-Type: application/json

{
  "nome": "pedro"
}

### DELETE
DELETE  http://localhost:3000/users/2